apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# namespace setting
- base/namespace.yaml
# My app setting
- base/actor-deployment.yaml
- base/learner-deployment.yaml
- base/learner-service.yaml
- base/ingress.yaml