apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# namespace setting
- base/namespace.yaml
# My app setting
- base/redis-deployment.yaml
- base/redis-service.yaml
- base/mysql-deployment.yaml
- base/mysql-service.yaml
- base/mongo-deployment.yaml
- base/mongo-service.yaml
- base/ingress.yaml