apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mykube
resources:
- base/redis-deployment.yaml
- base/redis-service.yaml
- base/mysql-deployment.yaml
- base/mysql-service.yaml
- base/mongo-deployment.yaml
- base/mongo-service.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
- base/ingress.yaml
patches:
- target:
    group: apps
    kind: Deployment
    name: argocd-server
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --rootpath=/argocd