resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
- base/redis-deployment.yaml
- base/redis-service.yaml
- base/mysql-deployment.yaml
- base/mysql-service.yaml
- base/mongo-deployment.yaml
- base/mongo-service.yaml
- base/ingress.yaml
- base/argocd-deployment.yaml
namespace: mykube