apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ml-ingress
  labels:
    app.kubernetes.io/name: ml-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /learner
        backend:
          service:
            name: mylearner
            port: 
              number: 6006