apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ml-ingress
  labels:
    app.kubernetes.io/name: ml-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - pathType: ImplementationSpecific
        path: /learner(/|$)(.*)
        backend:
          service:
            name: mylearner
            port: 
              number: 6006