apiVersion: apps/v1
kind: Deployment
metadata:
  name: learner-deployment
  namespace: myml
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: learner
  template:
    metadata:
      labels:
        app: learner
    spec:
      containers:
      - name: learner
        image: my-learner:latest
        imagePullPolicy: Always
        env:
        - name: REDIS_HOST
          value: "myredis.mykube"
        - name: REDIS_PORT
          value: "5080"
        ports:
        - containerPort: 6006
        resources:
          requests:
            memory: "2Gi"
            cpu: "2"
          limits:
            nvidia.com/gpu: "1"
            memory: "4Gi"
            cpu: "4"
