apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
- base/ingress.yaml
- base/argocd-db-app.yaml
- base/argocd-ml-app.yaml
patches:
- target:
    group: apps
    kind: Deployment
    name: argocd-server
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --rootpath=/argocd
- target:
    group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: argocd-application-controller
  patch: |-
    - op: replace
      path: /subjects/0/namespace
      value: argocd
    - op: replace
      path: /roleRef/name
      value: cluster-admin
- target:
    group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: argocd-server
  patch: |-
    - op: replace
      path: /subjects/0/namespace
      value: argocd