apiVersion: v1
kind: Namespace
metadata:
  name: myargocd
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: myargocd
type: Opaque
stringData:
  admin.password: yourpass
  admin.passwordMtime: "2026-01-31T00:00:00Z"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myargocd
  namespace: myargocd
spec:
  project: default
  source:
    repoURL: https://github.com/Naptwen/TOY_KUBE.git
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: mykube
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true