apiVersion: v1
kind: Namespace
metadata:
  name: mykube
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myargocd
  namespace: mykube
spec:
  project: default
  source:
    repoURL: https://github.com/Naptwen/TOY_KUBE.git
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: mykube
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true